### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by 3b** [3b/3b-winmd#1]
- [ ] test with other winmd files (WinRT, App SDK, etc)
- [ ] decide if it should generate a full ffi, or be a tool for generating project-specific subsets #2
- [ ] generate proper ffi defs (fix names, generate package definitions, etc)
- [ ] (optionally?) filter out ansi or unicode versions of things (A and W suffix)
- [ ] translate `typedef` and `GUID constant` structs properly
- [ ] generate something for the `GUID`s attached to `COM` structs
- [ ] accessors for sub-octet struct slots (c bit fields)
- [ ] add comments/docstrings for more custom attributes (docs, `const`, etc)
- [ ] write tests for struct/union layout generation (generate some C code to compare offsets against?)
- [ ] generate high-level wrappers
- [ ] clean up code
- [ ] api, documentation
- [ ] figure out the details of `COM` and decide if generating `com-on` definitions is enough for everything, or if some APIs could/should use something else #3
